# Generated by Django 5.2.6 on 2025-09-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="todo",
            name="complete",
            field=models.BooleanField(default=False),
        ),
    ]
